Lesson 1
CodectiveOrg/bootcamp-2024-free-nextjs-hashemi-st pull request #2
Opened 2024-12-15 15:01 UTC by hashemi-st

2024-12-15 18:09 UTC, BijanProgrammer requested changes

2024-12-15 18:09 UTC, BijanProgrammer commented on .gitignore
> -.vscode/
اینا رو باید به انتهای فایل اضافه کنید

2024-12-15 18:09 UTC, BijanProgrammer commented on README.md
> +# Created by https://www.toptal.com/developers/gitignore/api/webstorm,visualstudiocode,nextjs
اشتباهی محتوای .gitignore رو گذاشتید تو README.md

2024-12-16 10:32 UTC, hashemi-st commented on .gitignore
> -.vscode/
انجام شد.

2024-12-16 10:32 UTC, hashemi-st commented on README.md
> +# Created by https://www.toptal.com/developers/gitignore/api/webstorm,visualstudiocode,nextjs
بله درسته ممنون. اشتباهات رو در همین برنچ رفع و دوباره پوش کردم

2024-12-16 12:01 UTC, BijanProgrammer requested changes

2024-12-16 12:01 UTC, BijanProgrammer commented on .gitignore
طبق ویدئو باید محتوای gitignore رو از سایت gitignore.io بردارید

2024-12-16 15:53 UTC, hashemi-st commented on .gitignore
انجام شد.

2024-12-16 16:04 UTC, BijanProgrammer approved these changes

2024-12-19 17:42 UTC, merged